---
title: "Phyto_Chl_InnundationFigures"
author: "Alli Brady"
date: "3/22/2022"
output: html_document
---

```{r}
##Loading Libraries
library(ggplot2)
library(lubridate)
library(rcompanion)
library(viridis)
library(dplyr)
library(ggthemes)
library(tidyverse)
library(rcartocolor)
library(rstatix)
library(visreg)
library(plotly)
library(patchwork)
## Set WD and Bringing in Data
setwd('C:/Users/abrady/Documents/R/ltreport/WY2017_WY2019/')
light<-read.csv("data_clean/clean_light_dataset.csv")
phyto<-read.csv("data_raw/LT_phyto_density.csv")
chl<-read.csv("data_raw/LT_discrete_chla_RAW (1).csv")
inundation <- read_csv("data_raw/InundationWY2010toWY2019.csv")
```

```{r}
## Editing Data 
chl<- filter(chl,!Analyte%in% 'Pheo') # Dont need this analyte
light2<- light[ ,c(1,2,3,6,11,26)]  #pear down to useful columns
phyto2<-phyto[ ,c(1,2,3,37)]
colnames(light2)[1]='Date'           # changed weird column names
colnames(chl)[1]='StationCode'
chl<- filter(chl,StationCode%in% c('STTD','LIS','SHR')) #Useful Stations only
chl$Result<-as.numeric(chl$Result)  #as numeric value
```

```{r}
 ## Summarizing Data By Date and Station
Bio<-                            # total biovolume 
group_by(phyto2, Date, StationCode) %>%
summarize('biovolume' = sum(Biovolume.Density))  
Chl<-             #summarize chlorophyl by date/station  this takes he average of the sample and replicate sample
  group_by(chl, Date, StationCode) %>%
  summarize('Result' = mean(Result))  
```

```{r}
  ## Making a water year column for datasets
Bio$Date<-mdy(Bio$Date)
Bio$Year<-year(Bio$Date)
Bio$month<-month(Bio$Date)
Chl$Date<-mdy(Chl$Date)
Chl$Year<-year(Chl$Date)
Chl$month<-month(Chl$Date)
inundation$Date<-mdy(inundation$Date)
inundation$Year<-year(inundation$Date)
inundation$month<-month(inundation$Date)
Bio <- mutate(Bio, month = month(Date), 
              WaterYear = case_when(
                month %in% c(10,11,12) ~ Year +1,
                TRUE ~ Year
              ))                           
Bio$WaterYear<- as_factor(Bio$WaterYear)
Chl<- mutate(Chl, month = month(Date),   
             WaterYear = case_when(
               month %in% c(10,11,12) ~ Year +1,
               TRUE ~ Year
             ))                           
Chl$WaterYear<- as_factor(Chl$WaterYear)
Chl<- filter(Chl,!(WaterYear == "2020"))   #some 2020 data got in here
inundation<- mutate(inundation, month = month(Date), 
                    WaterYear = case_when(
                      month %in% c(10,11,12) ~ Year +1,
                      TRUE ~ Year
                    ))                           
inundation$WaterYear<- as_factor(inundation$WaterYear)
```

```{r}
### Taking out SHR for some analysis later on on ONLY TOE DRAIN (TD) Sites
BioTD<-filter(Bio, StationCode !="SHR") 
ChlTD<-filter(Chl,StationCode !="SHR")
## Screwtrap only datasets for inundation plots
ChlSTTD<-filter(ChlTD,StationCode !="LIS")
BioSTTD<-filter(BioTD, StationCode !="LIS") 
```

```{r}
##Set publication Theme- copied over
windowsFonts(Arial=windowsFont("TT Arial"))
theme_Publication <- function(base_size=12, base_family="Arial") {
  library(grid)
  library(ggthemes)
  (theme_foundation(base_size=base_size, base_family=base_family)
    + theme(plot.title = element_text(face = "bold",
                                      size = rel(1.2), hjust = 0.5),
            text = element_text(),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            panel.border = element_rect(colour = NA),
            axis.title = element_text(size = rel(1)),
            axis.title.y = element_text(angle=90,vjust =2),
            axis.title.x = element_text(vjust = -0.2),
            axis.text = element_text(), 
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            panel.grid.major = element_line(colour="#f0f0f0"),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.key.size= unit(0.2, "cm"),
            legend.spacing = unit(0, "cm"),
            plot.margin=unit(c(10,5,5,5),"mm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(face="bold")
    ))
  
}
```

```{r}
##Clorophyll at STTD Graph with Inundation Period
inundation <- read_csv("data_raw/InundationWY2010toWY2019.csv")
inundation$Date <- mdy(inundation$Date)
#Filter to relevant time period
inundation <-inundation %>%
  filter(Date>"2016-10-01" & Date<"2019-09-30") %>%
  mutate(Inundation2 = ifelse(lead(Inundation, 10) == "TRUE", "TRUE", Inundation),
         Inundation_n = ifelse(Inundation2 == "TRUE", 50, 0))
#Graph
 ##Chlorophyll over time 
 p2<- ggplot()+
  geom_line(data = ChlSTTD, aes(x= Date, y=Result,))+ 
  geom_col(data = inundation, aes(x = Date, y = Inundation_n), fill="light blue", alpha=0.6)+
  theme(legend.position = "right")+
   theme_Publication()+
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +
  theme(axis.text.x = element_text(size = 8, angle =90))+
  labs(colour="Innundation Period") +
  labs(x = "Date") + 
  labs(y = "Chlorophyll result",title="Chlorophyll at STTD") 
p2
```
```{r}
##Biovol by site over time with inundation -JUST STTD
inundation <-inundation %>%
  filter(Date>"2016-10-01" & Date<"2019-09-30") %>%
  mutate(Inundation2 = ifelse(lead(Inundation, 10) == "TRUE", "TRUE", Inundation),
         Inundation_n = ifelse(Inundation2 == "TRUE", 2.49e+07, 0))
#Graph
p3<- ggplot()+
  
  geom_col(data = inundation, aes(x = Date, y = Inundation_n), fill="light blue", alpha=0.6)+
  geom_line(data = BioSTTD, aes(x= Date, y=biovolume,))+ 
   ylim(0,2.49e+07)+
  theme_Publication() +
 
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +
  labs(colour="Innundation Period") +
  theme(axis.text.x = element_text(size = 8, angle =90))+
  labs(x = "Date", element_text(size=3)) + 
  labs(y = "Biovolume Density (??m3/mL)",title="Phytoplankton at STTD") 
p3
```



