---
title: "multivariate_drift_data"
author: "Catarina Pien"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
rm(list=ls(all=TRUE))

library(tidyverse)
library(lubridate)
library(viridis)
library(plotly)
library(readr)
library(here)
```


```{r}
root <- "WY2016_WY2019/data_clean"
driftOrderAbund<- read_csv(here::here(root, "clean_drift_order_abundant.csv"))%>%
  mutate(Date = lubridate::ymd(Date)) %>%
  ungroup()

inundation2 <- read_csv(here::here(root, "inundation2.csv")) %>%
  mutate(Date = lubridate::ymd(Date))
```

## NMDS

### Order
Complete Case Order
```{r}
Drift_Order_complete <- driftOrderAbund %>%
  filter(Order != "") %>%
  left_join(inundation2) %>%
  filter(!is.na(Inundation)) %>%
  rename(CPUE2 = CPUEDaily) %>%
  group_by(Station, Date, Order) %>%
  arrange(desc(Station, Date, Order, CPUE2)) %>%
  slice(1) %>% # there is one duplicate 12/21/2016 that is causing issues. All 0s
  ungroup()
```

Create matrix
```{r}
matOrder <- Drift_Order_complete %>% dplyr::select(c("Station", "Season1", "Season2", "Season3", "fWY", "WYClass", "Inundation", "fMonth", "Date", "Order", "CPUE2")) 

# Check no duplicates
check <- matOrder %>% group_by(Station, Date, Order) %>%
  mutate(n = n()) %>%
  filter(n > 1)

# Species Matrix
Order_w <- matOrder %>% pivot_wider(names_from = Order, values_from = CPUE2, values_fill = list(CPUE2=0)) %>% ungroup() %>%
mutate(fWY = as.factor(fWY),
         Inundation = as.factor(Inundation),
         Inundation = ifelse(Inundation == "FALSE", "No", "Yes"))

# Remove any row where there is no catch for the day.
Order_w2 <- Order_w %>% mutate(Total = dplyr::select(., Amphipoda:Tubificida) %>%  rowSums(na.rm = TRUE)) %>%
  filter(Total !=0)

# STTD only for inundation
Order_STTD <- Order_w %>% filter(Station == "STTD")

Order_STTD2 <- Order_STTD %>% mutate(Total = dplyr::select(., Amphipoda:Tubificida) %>%  rowSums(na.rm = TRUE)) %>%
  filter(Total !=0)
```


Run NMDS
```{r}
library(vegan)
# NMDS Order
nmdsOrder <- metaMDS(Order_w2[,10:29], distance="bray", k=3, trymax=400, autotransform = FALSE)
nmdsOrder

stressplot(nmdsOrder)


# STTD
nmdsOrderSTTD <- metaMDS(Order_STTD2[,10:29], distance="bray", k=3, trymax=400, autotransform = FALSE)
nmdsOrderSTTD

stressplot(nmdsOrderSTTD)

```

#### Plotting code from Rosie/Mallory
```{r}
source("NMDS_reference/plotNMDS.r")
#variables need to be factors in order to work to make centroids in Rosie's plotNMDS code
Drift_env1 <- Order_w2 %>%
  select(c(Station:Inundation)) %>%
  mutate(Station = as.factor(Station),
         fWY = as.factor(fWY),
         Season1 = as.factor(Season1),
         Season2 = as.factor(Season2),
         Season3 = as.factor(Season3))

Drift_env_STTD <- Order_STTD2 %>%
  select(c(Station:Inundation)) %>%
  mutate(Station = as.factor(Station),
         fWY = as.factor(fWY),
         Season1 = as.factor(Season1),
         Season2 = as.factor(Season2),
         Season3= as.factor(Season3))

#Rosie's plotNMDS code for report figures
plotStation <- PlotNMDS(nmdsOrder, Drift_env1, group = "Station", textp = FALSE)

plotWY <- PlotNMDS(nmdsOrder, Drift_env1, group = "fWY", textp = FALSE)

plotInun <- PlotNMDS(nmdsOrderSTTD, Drift_env_STTD, group = "Inundation", textp = FALSE)

plotSeason1 <- PlotNMDS(nmdsOrder, Drift_env1, group = "Season1", textp = FALSE)

plot150Season2 <- PlotNMDS(nmdsOrder, Drift_env1, group = "Season3", textp = FALSE)
```

```{r}
#tiff("Figures/fig_drift7_NMDS_Station_Drift.tiff", res=300, family = "sans", compression = "lzw")
#PlotNMDS(nmdsOrder, Drift_env1, group = "Station", textp = FALSE)
#dev.off()
```


Plot NMDS (this one)

```{r}
theme_NMDS <- theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank())
```

```{r nmdsplot, message = FALSE, warning = FALSE}
### NMDS scores
order.scores <- as.data.frame(scores(nmdsOrder))
species.scores <- as.data.frame(scores(nmdsOrder, "species"))
species.scores$species <- rownames(species.scores)

# Need a category to merge scores with the rest of env data
row.names(order.scores) <- row.names(Order_w2)
order.nmdsplot <- cbind(order.scores, Order_w2)

########### STTD version

### NMDS scores
order.scores2 <- as.data.frame(scores(nmdsOrderSTTD))
species.scores2 <- as.data.frame(scores(nmdsOrderSTTD, "species"))
species.scores2$species <- rownames(species.scores2)

# Need a category to merge scores with the rest of env data
row.names(order.scores2) <- row.names(Order_STTD2)
order.nmdsplot2 <- cbind(order.scores2, Order_STTD2)



# Plotting Function
f_plotNMDS <- function(nmdsDf, covariate, colors = cols, legendtitle=covariate) {
  
  ggplot(nmdsDf, aes(NMDS1, NMDS2, color = .data[[covariate]])) + 
  geom_point(aes(shape = .data[[covariate]]), size = 3, position = position_jitter(.1) ) +
  # #geom_text(aes(label = WYClass)) +
  stat_ellipse(type = 't', size = 1, aes(linetype = .data[[covariate]])) +
  annotate("text", x = min(order.nmdsplot$NMDS1) + 0.25, y = min(order.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsOrder$stress,3))) + # Add stress to plot
  scale_color_manual(values = colors, name = legendtitle) +
    labs(shape = legendtitle, linetype = legendtitle, color = legendtitle) +
  theme_NMDS
}

cols <- c("#414487FF",  "#7AD151FF", "#FDE725FF")
cols2 <- c("#414487FF",  "#22A884FF", "#7AD151FF", "#FDE725FF")

(nmds_station <- f_plotNMDS(order.nmdsplot, "Station", cols))
(nmds_WY <- f_plotNMDS(order.nmdsplot, "fWY", cols, "Water Year")) 
(nmds_inundation <- f_plotNMDS(order.nmdsplot2, "Inundation", cols, "Inundation") )
nmds_season1 <- f_plotNMDS(order.nmdsplot, "Season1", cols)
(nmds_season3 <- f_plotNMDS(order.nmdsplot, "Season3", cols2, "Season"))
nmds_season3_STTD <- f_plotNMDS(order.nmdsplot2, "Season3", cols2, "Season")
```

```{r}
tiff("Figures/fig_drift7_NMDS_Station_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",  family = "sans", compression = "lzw")
nmds_station
dev.off()

tiff("Figures/fig_drift8_NMDS_WY_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",family = "sans", compression = "lzw")
nmds_WY
dev.off()

tiff("Figures/fig_drift9_NMDS_Inundation_Drift.tiff", res=300, width = 5, height = 3,5, units = "in",family = "sans", compression = "lzw")
nmds_inundation
dev.off()

tiff("Figures/fig_drift10_NMDS_Season_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",family = "sans", compression = "lzw")
nmds_season3
dev.off()

tiff("Figures/fig_drift10_NMDS_SeasonSTTD_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",family = "sans", compression = "lzw")
nmds_season3_STTD
dev.off()
```

Other plotting method
```{r}
############ Plots
# Option 2
# With species scores and boxes

# Make the datasets for the boxes
grp.a <- order.nmdsplot[order.nmdsplot$Station =="STTD", ][chull(order.nmdsplot[order.nmdsplot$Station ==
    "STTD", c("NMDS1", "NMDS2")]), ]  # hull values for grp A
grp.b <- order.nmdsplot[order.nmdsplot$Station =="SHR", ][chull(order.nmdsplot[order.nmdsplot$Station ==
    "SHR", c("NMDS1", "NMDS2")]), ]  # hull values for grp B
hull.data0 <- rbind(grp.a, grp.b)  #combine grp.a and grp.b


# Plot
ggplot() + 
  geom_point(data = order.nmdsplot, aes(x = NMDS1, y = NMDS2, color = Station),
             position = position_jitter(.1)) +
  geom_text(data = order.nmdsplot, aes(NMDS1, NMDS2, label = WYClass, color = Station)) +
  geom_text(data = species.scores, aes(x = NMDS1, y = NMDS2, label= species), color = "black", size = 3.5) +
  theme_minimal() +
  annotate("text", x = min(order.nmdsplot$NMDS1), y = min(order.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsOrder$stress,3))) + # Add stress to plot
  geom_polygon(data=hull.data0,aes(x=NMDS1,y=NMDS2,fill=Station,group=Station),alpha=0.30) 
```


Inundation for STTD
```{r}
# Make the datasets for the boxes
grp.a2 <- order.nmdsplot2[order.nmdsplot2$Inundation2 =="TRUE", ][chull(order.nmdsplot2[order.nmdsplot2$Inundation2 ==
    "TRUE", c("NMDS1", "NMDS2")]), ]  # hull values for grp A
grp.b2 <- order.nmdsplot2[order.nmdsplot2$Inundation2 =="FALSE", ][chull(order.nmdsplot2[order.nmdsplot2$Inundation2 ==
    "FALSE", c("NMDS1", "NMDS2")]), ]  # hull values for grp B
hull.dataSTTD <- rbind(grp.a2, grp.b2)  #combine grp.a and grp.b


# Plot
ggplot() + 
  geom_point(data = order.nmdsplot2, aes(x = NMDS1, y = NMDS2, color = Inundation2),
             position = position_jitter(.1)) +
  geom_text(data = order.nmdsplot2, aes(NMDS1, NMDS2, label = WYClass, color = Inundation2)) +
  geom_text(data = species.scores2, aes(x = NMDS1, y = NMDS2, label= species), color = "black", size = 3.5) +
  theme_minimal() +
  annotate("text", x = min(order.nmdsplot2$NMDS1), y = min(order.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsOrderSTTD$stress,3))) + # Add stress to plot
  geom_polygon(data=hull.dataSTTD,aes(x=NMDS1,y=NMDS2,fill=Inundation2,group=Inundation2),alpha=0.30) 
```


### Family

Complete Case
```{r}

Drift_Family_complete <- driftFamilyAbund %>%
  filter(!is.na(Family)) %>%
  filter(Family != "") %>%
  left_join(inundation2) %>%
  filter(!is.na(Inundation2)) %>%
  rename(CPUE2 = CPUEDay) %>%
  arrange(Station, Date, Family)

```


Create matrix
```{r}
matFamily <- Drift_Family_complete %>% dplyr::select(c("Station", "Season1", "Season2", "fWY", "WYClass", "Inundation2", "fMonth", "Date", "Family", "CPUE2"))

# Species Matrix
Family_w <- matFamily %>% pivot_wider(names_from = Family, values_from = CPUE2, values_fill = list(CPUE2=0)) %>% ungroup()

# Remove any row where there is no catch for the day.
Family_w2 <- Family_w %>% mutate(Total = dplyr::select(., Ceratopogonidae:Psychodidae) %>%  rowSums(na.rm = TRUE)) %>%
  filter(Total !=0)


####### STTD only
Family_STTD <- Family_w %>% filter(Station == "STTD")

```


```{r}
library(vegan)
# NMDS Family
nmdsFamily <- metaMDS(Family_w2[,8:28], distance="bray", k=3, trymax=400, autotransform = FALSE)
nmdsFamily

stressplot(nmdsFamily)

########## STTD

# NMDS Family
nmdsFamilySTTD <- metaMDS(Family_STTD[,8:28], distance="bray", k=3, trymax=400, autotransform = FALSE)
nmdsFamilySTTD

stressplot(nmdsFamilySTTD)
```

```{r nmdsplot, message = FALSE, warning = FALSE}
### NMDS scores
family.scores <- as.data.frame(scores(nmdsFamily))
species.scoresF <- as.data.frame(scores(nmdsFamily, "species"))
species.scoresF$species <- rownames(species.scoresF)

# Need a category to merge scores with the rest of env data
row.names(family.scores) <- row.names(Family_w)
family.nmdsplot <- cbind(family.scores, Family_w)


####### STTD

### NMDS scores
family.scores2 <- as.data.frame(scores(nmdsFamilySTTD))
species.scores2F <- as.data.frame(scores(nmdsFamilySTTD, "species"))
species.scores2F$species <- rownames(species.scores2F)

# Need a category to merge scores with the rest of env data
row.names(family.scores2) <- row.names(Family_STTD)
family.nmdsplot2 <- cbind(family.scores2, Family_STTD)



###  Plots
# Station
ggplot(family.nmdsplot, aes(NMDS1, NMDS2, color = Station)) + 
  geom_point(aes(shape = WYClass),position = position_jitter(.1) ) +
  geom_text(aes(label = WYClass)) +
  stat_ellipse(type = 't', size = 1) +
  scale_color_viridis(discrete = TRUE) +
  annotate("text", x = min(family.nmdsplot$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamily$stress,3))) + # Add stress to plot
  theme_minimal() 

# Year
ggplot(family.nmdsplot, aes(NMDS1, NMDS2, color = fWY)) + 
  geom_point(position = position_jitter(.1)) +
  geom_text(aes(label = Station)) +
  stat_ellipse(type = 't', size = 1) +
  scale_color_viridis(discrete = TRUE) +
  annotate("text", x = min(family.nmdsplot$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamily$stress,3))) + # Add stress to plot
  theme_minimal() 

# Season
ggplot(family.nmdsplot, aes(NMDS1, NMDS2, color = Season2)) + 
  geom_point(position = position_jitter(.1)) +
  geom_text(aes(label = Station)) +
  stat_ellipse(type = 't', size = 1) +
  scale_color_viridis(discrete = TRUE) +
  annotate("text", x = min(family.nmdsplot$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamily$stress,3))) + # Add stress to plot
  theme_minimal() 

# Season (STTD)
ggplot(family.nmdsplot2, aes(NMDS1, NMDS2, color = Season2)) + 
  geom_point(position = position_jitter(.1)) +
  geom_text(aes(label = Station)) +
  stat_ellipse(type = 't', size = 1) +
  scale_color_viridis(discrete = TRUE) +
  annotate("text", x = min(family.nmdsplot2$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamilySTTD$stress,3))) + # Add stress to plot
  theme_minimal() 

# Inundation
ggplot(family.nmdsplot2, aes(NMDS1, NMDS2, color = Inundation2)) + 
  geom_point(position = position_jitter(.1)) +
  geom_text(aes(label = Station)) +
  stat_ellipse(type = 't', size = 1) +
  scale_color_viridis(discrete = TRUE) +
  annotate("text", x = min(family.nmdsplot2$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamilySTTD$stress,3))) + # Add stress to plot
  theme_minimal() 


# Year (STTD)
ggplot(family.nmdsplot2, aes(NMDS1, NMDS2, color = fWY)) + 
  geom_point(position = position_jitter(.1)) +
  geom_text(aes(label = Station)) +
  stat_ellipse(type = 't', size = 1) +
  scale_color_viridis(discrete = TRUE) +
  annotate("text", x = min(family.nmdsplot$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamilySTTD$stress,3))) + # Add stress to plot
  theme_minimal() 



# Option 2
# With species scores and boxes

# Make the datasets for the boxes
grp.aF <- family.nmdsplot[family.nmdsplot$Station =="STTD", ][chull(family.nmdsplot[family.nmdsplot$Station ==
    "STTD", c("NMDS1", "NMDS2")]), ]  # hull values for grp A
grp.bF <- family.nmdsplot[family.nmdsplot$Station =="SHR", ][chull(family.nmdsplot[family.nmdsplot$Station ==
    "SHR", c("NMDS1", "NMDS2")]), ]  # hull values for grp B
hull.dataF <- rbind(grp.aF, grp.bF)  #combine grp.a and grp.b


# Plot
ggplot() + 
  geom_point(data = family.nmdsplot, aes(x = NMDS1, y = NMDS2, color = Station),
             position = position_jitter(.1)) +
  geom_text(data = family.nmdsplot, aes(NMDS1, NMDS2, label = WYClass, color = Station)) +
  geom_text(data = species.scores, aes(x = NMDS1, y = NMDS2, label= species), color = "black", size = 3.5) +
  theme_minimal() +
  annotate("text", x = min(family.nmdsplot$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamily$stress,3))) + # Add stress to plot
  geom_polygon(data=hull.dataF,aes(x=NMDS1,y=NMDS2,fill=Station,group=Station),alpha=0.30) 


```

Inundation for STTD
```{r}
# Make the datasets for the boxes
grp.aF2 <- family.nmdsplot2[family.nmdsplot2$Inundation2 =="TRUE", ][chull(family.nmdsplot2[family.nmdsplot2$Inundation2 ==
    "TRUE", c("NMDS1", "NMDS2")]), ]  # hull values for grp A
grp.bF2 <- family.nmdsplot2[family.nmdsplot2$Inundation2 =="FALSE", ][chull(family.nmdsplot2[family.nmdsplot2$Inundation2 ==
    "FALSE", c("NMDS1", "NMDS2")]), ]  # hull values for grp B
hull.dataF2 <- rbind(grp.aF2, grp.bF2)  #combine grp.a and grp.b


# Plot
ggplot() + 
  geom_point(data = family.nmdsplot2, aes(x = NMDS1, y = NMDS2, color = Inundation2),
             position = position_jitter(.1)) +
  geom_text(data = family.nmdsplot2, aes(NMDS1, NMDS2, label = WYClass, color = Inundation2)) +
  geom_text(data = species.scores, aes(x = NMDS1, y = NMDS2, label= species), color = "black", size = 3.5) +
  theme_minimal() +
  annotate("text", x = min(family.nmdsplot2$NMDS1), y = min(family.nmdsplot$NMDS2), label = paste('Stress = ', round(nmdsFamilySTTD$stress,3))) + # Add stress to plot
  geom_polygon(data=hull.dataF2,aes(x=NMDS1,y=NMDS2,fill=Inundation2,group=Inundation2),alpha=0.30) 
```



## Add PERMANOVA
### Order
```{r}
# Row standardization - subset species columns only
order.st <- decostand(Order_w2[,10:29], method = 'total')
order.st2 <- decostand(Order_STTD2[,10:29], method = 'total')

# Individual permanova models

# Both stations
(perm.Order.Station <- adonis(formula = order.st~Station, data = Order_w2, method = "bray", permutations = 99))

(perm.Order.Yr <- adonis(formula = order.st~ fWY , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.Season <- adonis(formula = order.st~ Season3 , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeason <- adonis(formula = order.st~ Season3 + Station , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeasonYear <- adonis(formula = order.st~ Season3 + Station + fWY , data = Order_w2, method = "bray", permutations = 99))

(perm.int1 <- adonis(formula = order.st~Station:fWY, data = Order_w2, method = "bray", permutations = 99))

(perm.int2 <- adonis(formula = order.st~Station:Season3, data = Order_w2, method = "bray", permutations = 99))

(perm.int3 <- adonis(formula = order.st~fWY:Season3, data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeasonYearInt2 <- adonis(formula = order.st~ Season3 + Station + fWY + Station:Season3 , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeasonYearInt2Int1 <- adonis(formula = order.st~ Season3 + Station + fWY + Station:Season3 + fWY:Station , data = Order_w2, method = "bray", permutations = 99))


# STTD only
(perm.Order.Season <- adonis(formula = order.st2~ Season3 , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.Inund <- adonis(formula = order.st2~Inundation, data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.fWY <- adonis(formula = order.st2~ fWY , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.SeasonInundInt <- adonis(formula = order.st2~ Season3:Inundation , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.SeasonfWYInt <- adonis(formula = order.st2~ Season3:fWY , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.fWYInundInt <- adonis(formula = order.st2~ fWY:Inundation , data = Order_STTD2, method = "bray", permutations = 99))



(perm.Order.InundSeason <- adonis(formula = order.st2~Season3 + Inundation, data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.InundSeasonYear <- adonis(formula = order.st2~Season3 + Inundation + fWY, data = Order_STTD2, method = "bray", permutations = 99))

# Interactions don't help
(perm.Order.all1 <- adonis(formula = order.st2~Season3 + Inundation + fWY + fWY:Inundation, data = Order_STTD2, method = "bray", permutations = 99))

```

*For both, Inundation + Season + fWY explains 17% variation*
*For STTD, Inundation + Season explains 24% variation*

### Family
```{r}
# Row standardization
family.st <- decostand(Family_w[,9:27], method = 'total')
family.st2 <- decostand(Family_STTD[,9:27], method = 'total')

# Individual permanova models

# Both stations
(perm.Family.Station <- adonis(formula = family.st~Station, data = Family_w, method = "bray", permutations = 99))

(perm.Family.Yr <- adonis(formula = family.st~ fWY , data = Family_w, method = "bray", permutations = 99))

(perm.Family.Season <- adonis(formula = family.st~ Season2 , data = Family_w, method = "bray", permutations = 99))

(perm.Family.StationSeason <- adonis(formula = family.st~ Season2 + Station , data = Family_w, method = "bray", permutations = 99))

(perm.Family.StationSeasonYear <- adonis(formula = family.st~ Season2 + Station + fWY , data = Family_w, method = "bray", permutations = 99))

# STTD only
(perm.Family.Season <- adonis(formula = family.st2~ Season2 , data = Family_STTD, method = "bray", permutations = 99))

(perm.Family.Inund <- adonis(formula = family.st2~Inundation2, data = Family_STTD, method = "bray", permutations = 99))

(perm.Family.InundSeason <- adonis(formula = family.st2~Inundation2 + Season2, data = Family_STTD, method = "bray", permutations = 99))

(perm.Family.InundSeasonYear <- adonis(formula = family.st2~Inundation2 + Season2 +fWY, data = Family_STTD, method = "bray", permutations = 99))

(perm.Family.InundSeasonYear2 <- adonis(formula = family.st2~Inundation2 + Season2  + Season2:fWY, data = Family_STTD, method = "bray", permutations = 99))

```
