---
title: "multivariate_drift_data"
author: "Catarina Pien"
date: "2/14/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
rm(list=ls(all=TRUE))

library(tidyverse)
library(lubridate)
library(viridis)
library(plotly)
library(readr)
library(here)
```

# Multivariate Code

Read in data
```{r}
root <- "WY2017_WY2019/data_clean"
driftOrderAbund<- read_csv(here::here(root, "clean_drift_order_abundant.csv"))%>%
  mutate(Date = lubridate::ymd(Date)) %>%
  ungroup()

inundation2 <- read_csv(here::here(root, "inundation2.csv")) %>%
  mutate(Date = lubridate::ymd(Date))
```

## Order
Complete Case Order
```{r}
Drift_Order_complete <- driftOrderAbund %>%
  filter(Order != "") %>%
  left_join(inundation2) %>%
  filter(!is.na(Inundation)) %>%
  rename(CPUE2 = CPUEDaily) %>%
  group_by(Station, Date, Order) %>%
  arrange(Station, Date, Order, desc(CPUE2)) %>%
  slice(1) %>% # there is one duplicate 12/21/2016 that is causing issues. All 0s
  ungroup()
```

## NMDS

### Create matrix
```{r}
matOrder <- Drift_Order_complete %>% dplyr::select(c("Station", "Season1", "Season2", "Season3", "fWY", "WYClass", "Inundation", "fMonth", "Date", "Order", "CPUE2")) 

# Check no duplicates
check <- matOrder %>% group_by(Station, Date, Order) %>%
  mutate(n = n()) %>%
  filter(n > 1)

# Species Matrix
Order_w <- matOrder %>% pivot_wider(names_from = Order, values_from = CPUE2, values_fill = list(CPUE2=0)) %>% ungroup() %>%
mutate(fWY = as.factor(fWY),
         Inundation = as.factor(Inundation),
         Inundation = ifelse(Inundation == "FALSE", "No", "Yes"))

# Remove any row where there is no catch for the day.
Order_w2 <- Order_w %>% mutate(Total = dplyr::select(., Amphipoda:Tubificida) %>%  rowSums(na.rm = TRUE)) %>%
  filter(Total !=0)

# STTD only for inundation
Order_STTD <- Order_w %>% filter(Station == "STTD")

Order_STTD2 <- Order_STTD %>% mutate(Total = dplyr::select(., Amphipoda:Tubificida) %>%  rowSums(na.rm = TRUE)) %>%
  filter(Total !=0)
```


### Run NMDS
```{r}
library(vegan)
# NMDS Order
nmdsOrder <- metaMDS(Order_w2[,10:29], distance="bray", k=3, trymax=400, autotransform = FALSE)
nmdsOrder

stressplot(nmdsOrder)

# STTD
nmdsOrderSTTD <- metaMDS(Order_STTD2[,10:29], distance="bray", k=3, trymax=400, autotransform = FALSE)
nmdsOrderSTTD

stressplot(nmdsOrderSTTD)

```

```{r}
save(nmdsOrder, nmdsOrderSTTD, file = here(root, "nmdsResults.Rdata"))
```

```{r}
load(here(root, "nmdsResults.Rdata"))
```

### Plot NMDS

#### Plotting code from Rosie/Mallory
```{r}
source("NMDS_reference/plotNMDS.r")
#variables need to be factors in order to work to make centroids in Rosie's plotNMDS code
Drift_env1 <- Order_w2 %>%
  select(c(Station:Inundation)) %>%
  mutate(Station = as.factor(Station),
         fWY = as.factor(fWY),
         Season1 = as.factor(Season1),
         Season2 = as.factor(Season2),
         Season3 = as.factor(Season3))

Drift_env_STTD <- Order_STTD2 %>%
  select(c(Station:Inundation)) %>%
  mutate(Station = as.factor(Station),
         fWY = as.factor(fWY),
         Season1 = as.factor(Season1),
         Season2 = as.factor(Season2),
         Season3= as.factor(Season3))

#Rosie's plotNMDS code for report figures
plotStation <- PlotNMDS(nmdsOrder, Drift_env1, group = "Station", textp = FALSE)

plotWY <- PlotNMDS(nmdsOrder, Drift_env1, group = "fWY", textp = FALSE)

plotInun <- PlotNMDS(nmdsOrderSTTD, Drift_env_STTD, group = "Inundation", textp = FALSE)

plotSeason1 <- PlotNMDS(nmdsOrder, Drift_env1, group = "Season1", textp = FALSE)

plot150Season2 <- PlotNMDS(nmdsOrder, Drift_env1, group = "Season3", textp = FALSE)
```

```{r}
#tiff("Figures/fig_drift7_NMDS_Station_Drift.tiff", res=300, family = "sans", compression = "lzw")
#PlotNMDS(nmdsOrder, Drift_env1, group = "Station", textp = FALSE)
#dev.off()
```


#### Cat's plotting code (this one)

```{r}
theme_NMDS <- theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(),
legend.position = "top") 
```

##### NMDS function
```{r}
#### nmdsResult: input your nmds object
#### speciesPredictorMatrix: input your matrix used to run your nmds. It should include both your species columns as well as any predictor (e.g. station, year, grouping)
#### covariate: what covariate do you want to group by? This needs to be in quotes when you call the function.
#### If you don't want species labels to show up, comment out the 'gg_repel' call and the scale_x_continuous call. 
#### legendtitle is what you want your legend title to be, if you want it to be named differently from your covariate name

f_plotNMDS <- function(nmdsResult, speciesPredictorMatrix, covariate, colors = cols, legendtitle=covariate) {
  
# Calculate scores and prepare data frame for plotting
nmds.scores <- as.data.frame(scores(nmdsResult, "sites"))
species.scores <- as.data.frame(scores(nmdsResult, "species"))
species.scores$species <- rownames(species.scores)

# Need a category to merge scores with the rest of env data
row.names(nmds.scores) <- row.names(speciesPredictorMatrix)
df.nmdsplot <- cbind(nmds.scores, speciesPredictorMatrix)
  
  # extends the plot a little to include species labels that are a bit stretched out; may need to modify based on your data
  limits_x = c(min(species.scores$NMDS1-1), max(species.scores$NMDS1+1))
  limits_y = c(min(species.scores$NMDS2-0.1), max(species.scores$NMDS2+0.1))
  
  # plot
  ggplot(df.nmdsplot, aes(NMDS1, NMDS2)) +
  geom_point(aes(color = .data[[covariate]],shape = .data[[covariate]]), size = 3, position = position_jitter(.1) ) +
  ggrepel::geom_text_repel(data = species.scores, aes(label = species), max.overlaps = 12) + #try to avoid overlapping labels
  stat_ellipse(type = 't', size = 1, aes(color = .data[[covariate]],linetype = .data[[covariate]])) +
  annotate("text", x = min(df.nmdsplot$NMDS1) + 0.25, y = min(df.nmdsplot$NMDS2) -0.05, label = paste('Stress = ', round(nmdsResult$stress,3))) + # Add stress to plot
  scale_color_manual(values = colors, name = legendtitle) +
  scale_x_continuous(limits = limits_x) + 
  #scale_y_continuous(limits = limits_y) + # include if you want to edit y limits
  labs(shape = legendtitle, linetype = legendtitle, color = legendtitle) +
  theme_NMDS +
    theme(legend.position = "top")
}

```

##### Make plots
```{r}
cols <- c("#414487FF",  "#7AD151FF", "#FFA500")
cols2 <- c("#414487FF",  "#22A884FF", "#7AD151FF", "#FFA500")
nmdsOrder$Season3 <- factor(nmdsOrder$Season3, levels = c("Fall", "Winter", "Spring", "Summer"))

(nmds_station <- f_plotNMDS(nmdsResult = nmdsOrder, speciesPredictorMatrix = Order_w2,  covariate = "Station", colors = cols))

(nmds_WY <- f_plotNMDS(nmdsOrder, Order_w2,  "fWY", cols, legendtitle = "Water Year"))

(nmds_inundation <- f_plotNMDS(nmdsOrderSTTD, Order_STTD2,  "Inundation", cols))

(nmds_season3 <- f_plotNMDS(nmdsOrder, Order_w2,  "Season3", cols2, legendtitle = "Season"))

#nmds_season1 <- f_plotNMDS(nmdsOrder, Order_w2,  "Season1", cols)
(nmds_season3_STTD <- f_plotNMDS(nmdsOrderSTTD, Order_STTD2, "Season3", cols2, "Season"))
```

##### Combine NMDS plots
```{r}
library(ggpubr)

tiff("WY2017_WY2019/figures/fig_drift_NMDS_All_Drift_v2.tiff", res=300, width = 10, height = 8.5, units = "in",  family = "sans", compression = "lzw")
ggarrange(nmds_station, nmds_season3, nmds_season3_STTD, nmds_inundation, ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"))
dev.off()

```




##### Save plots individually
```{r}
tiff("figures/fig_drift7_NMDS_Station_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",  family = "sans", compression = "lzw")
nmds_station
dev.off()

tiff("figures/fig_drift8_NMDS_WY_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",family = "sans", compression = "lzw")
nmds_WY
dev.off()

tiff("figures/fig_drift9_NMDS_Inundation_Drift.tiff", res=300, width = 5, height = 3,5, units = "in",family = "sans", compression = "lzw")
nmds_inundation
dev.off()

tiff("figures/fig_drift10_NMDS_Season_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",family = "sans", compression = "lzw")
nmds_season3
dev.off()

tiff("figures/fig_drift10_NMDS_SeasonSTTD_Drift.tiff", res=300, width = 5, height = 3.5, units = "in",family = "sans", compression = "lzw")
nmds_season3_STTD
dev.off()
```


## PERMANOVA
### Order
```{r}
# Row standardization - subset species columns only
order.st <- decostand(Order_w2[,10:29], method = 'total')
order.st2 <- decostand(Order_STTD2[,10:29], method = 'total')

# Individual permanova models

# Both stations
(perm.Order.Station <- adonis(formula = order.st~Station, data = Order_w2, method = "bray", permutations = 99))

(perm.Order.Yr <- adonis(formula = order.st~ fWY , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.Season <- adonis(formula = order.st~ Season3 , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeason <- adonis(formula = order.st~ Season3 + Station , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeasonYear <- adonis(formula = order.st~ Season3 + Station + fWY , data = Order_w2, method = "bray", permutations = 99))

(perm.int1 <- adonis(formula = order.st~Station:fWY, data = Order_w2, method = "bray", permutations = 99))

(perm.int2 <- adonis(formula = order.st~Station:Season3, data = Order_w2, method = "bray", permutations = 99))

(perm.int3 <- adonis(formula = order.st~fWY:Season3, data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeasonYearInt2 <- adonis(formula = order.st~ Season3 + Station + fWY + Station:Season3 , data = Order_w2, method = "bray", permutations = 99))

(perm.Order.StationSeasonYearInt2Int1 <- adonis(formula = order.st~ Season3 + Station + fWY + Station:Season3 + fWY:Station , data = Order_w2, method = "bray", permutations = 99))


# STTD only
(perm.Order.Season <- adonis(formula = order.st2~ Season3 , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.Inund <- adonis(formula = order.st2~Inundation, data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.fWY <- adonis(formula = order.st2~ fWY , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.SeasonInundInt <- adonis(formula = order.st2~ Season3:Inundation , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.SeasonfWYInt <- adonis(formula = order.st2~ Season3:fWY , data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.fWYInundInt <- adonis(formula = order.st2~ fWY:Inundation , data = Order_STTD2, method = "bray", permutations = 99))



(perm.Order.InundSeason <- adonis(formula = order.st2~Season3 + Inundation, data = Order_STTD2, method = "bray", permutations = 99))

(perm.Order.InundSeasonYear <- adonis(formula = order.st2~Season3 + Inundation + fWY, data = Order_STTD2, method = "bray", permutations = 99))

# Interactions don't help
(perm.Order.all1 <- adonis(formula = order.st2~Season3 + Inundation + fWY + fWY:Inundation, data = Order_STTD2, method = "bray", permutations = 99))

```

*For both, Inundation + Season + fWY explains 17% variation*
*For STTD, Inundation + Season explains 24% variation*

