---
title: "LT Report Water Quality"
author: "Haley"
date: "1/14/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load libraries
library(tidyverse)
library(lubridate)
library(rcompanion)
library(xlsx)
library(stats)
library(viridis)
library(ggthemes)
library(plyr)
library(magrittr)
library(plotly)
library(readxl)
library(here)

library(extrafont)
```
#setup
```{r}
#setwd("Y:\\YB_Manuscripts, Reports, Newsletters (AEU)\\YoloBypass_AnnualReport_LowerTrophic\\Lower Trophic Report_2017-2019\\Water Quality")
#WQ<- read.csv(file ="discrete_environmental_LTreport_WY2017-WY2019.csv")
root <- "WY2017_WY2019/WQ_Chl"
WQ<- read.csv(here::here(root, "discrete_environmental_LTreport_WY2017-WY2019.csv"))

# Remove NA data points (when dates for both sites are the exact 365). Must remove NA to initially calculate mean, 
WQ<-WQ[!is.na(WQ$WaterTemp),]

WQ$WaterTemp <- as.numeric(as.character(WQ$WaterTemp))

WQ$Date<-mdy(WQ$Date)

WQ <- WQ %>% filter(DO!= 0.00)

View(WQ)
```
#create publication theme
```{r}
windowsFonts(Arial=windowsFont("TT Arial"))
theme_Publication <- function(base_size=12, base_family="Arial") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.key.size= unit(0.2, "cm"),
               legend.spacing = unit(0, "cm"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

```

#Temperature Plot
```{r}
tempplot <- ggplot() + 
  geom_line(data=WQ, aes(x=Date, y=WaterTemp, color=StationCode, linetype=StationCode), size=1) +
  scale_color_viridis(discrete=TRUE)+
  theme_Publication() + #or whatever ggtheme you want
  labs(x = "Date", y = "Temperature (?C)") +
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +# Changed date format 
  theme(axis.text.x = element_text(size = 8, angle =90))+ ##Changed dates to vertical
  theme(panel.grid.major = element_line(colour = "gray93",size=0.01), panel.grid.minor = element_blank())  #stylist choice, you can mess with this or not include it at all to stay with the R default
  #labs(colour = "Site") +
  #theme(plot.title = element_text(hjust = 0.5)) #not necessary


tempplot
tiff(filename = "WQFigs\\TempPlot.tiff", res = 300, width = 7, height = 5, family = "sans", units = "in", compression = "lzw")
(tempplot)

dev.off()

summary(WQ$WaterTemp)
   # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   # 6.20   10.90   15.60   15.84   20.40   27.10 

tp<-ggplotly(tempplot)
 tp 
 
WQ$month<-month(WQ$Date) 
 WQTD<-filter(WQ, StationCode !="SHR") 
 WQSHR<-filter(WQ, StationCode =="SHR") 
 summary (WQTD$WaterTemp)
 summary(WQSHR$WaterTemp)
 
WQWintTD<-subset(WQTD,month<=3)
WQWintS<-subset(WQSHR,month<=3)
#WQFall<-subset(WQ,month>=10 & month<=12)
WQFallTD<-subset(WQTD,month>=10 & month<=12)
WQFallS<-subset(WQSHR,month>=10 & month<=12)
WQSprTD<-subset(WQTD,month>=4 & month<=6)
WQSprS<-subset(WQSHR,month>=4 & month<=6)
WQSummTD<-subset(WQTD,month>=7 & month<=9)
WQSummS<-subset(WQSHR,month>=7 & month<=9)

 summary (WQFallTD$WaterTemp)
 summary(WQFallS$WaterTemp)

 summary (WQSprTD$WaterTemp)
 summary(WQSprS$WaterTemp)

summary (WQWintTD$WaterTemp)
 summary(WQWintS$WaterTemp)
 
  summary(WQSummTD$WaterTemp)
 summary(WQSummS$WaterTemp)
```
#Turbidity
```{r}
turbplot <- ggplot() + 
  geom_line(data=WQ, aes(x=Date, y=Turbidity, color=StationCode, linetype=StationCode), size=1) +
  scale_color_viridis(discrete=TRUE)+
  theme_Publication() + #or whatever ggtheme you want
  labs(x = "Date", y = "Turbidity (FNU)") +
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +# Changed date format 
  theme(axis.text.x = element_text(size = 8, angle =90))+ ##Changed dates to vertical
  theme(panel.grid.major = element_line(colour = "gray93",size=0.01), panel.grid.minor = element_blank())  #stylist choice, you can mess with this or not include it at all to stay with the R default
  #labs(colour = "Site") +
  #theme(plot.title = element_text(hjust = 0.5)) #not necessary


turbplot

```
#DO
```{r}
DOplot <- ggplot() + 
  geom_line(data=WQ, aes(x=Date, y=DO, color=StationCode, linetype=StationCode), size=1) +
  scale_color_viridis(discrete=TRUE)+
  theme_Publication() + #or whatever ggtheme you want
  labs(x = "Date", y = "Dissovled Oxygen") +
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +# Changed date format 
  theme(axis.text.x = element_text(size = 8, angle =90))+ ##Changed dates to vertical
  theme(panel.grid.major = element_line(colour = "gray93",size=0.01), panel.grid.minor = element_blank())  #stylist choice, you can mess with this or not include it at all to stay with the R default
  #labs(colour = "Site") +
  #theme(plot.title = element_text(hjust = 0.5)) #not necessary


DOplot

tiff(filename = "PhytoChloroOutputFigs/DOPlot.tiff", res = 300, width = 9, height = 5, family = "sans", units = "in", compression = "lzw")
(DOplot) 
dev.off()

DO<-ggplotly(DOplot)
 DO
```
#Conductivity
```{r}
SpCndplot <- ggplot() + 
  geom_line(data=WQ, aes(x=Date, y=SpCnd, color=StationCode, linetype=StationCode), size=1) +
  scale_color_viridis(discrete=TRUE)+
  theme_Publication() + #or whatever ggtheme you want
  labs(x = "Date", y = "Specific Conductivity") +
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +# Changed date format 
  theme(axis.text.x = element_text(size = 8, angle =90))+ ##Changed dates to vertical
  theme(panel.grid.major = element_line(colour = "gray93",size=0.01), panel.grid.minor = element_blank())  #stylist choice, you can mess with this or not include it at all to stay with the R default
  #labs(colour = "Site") +
  #theme(plot.title = element_text(hjust = 0.5)) #not necessary

SpCndplot
```
#Secchi
```{r}
Seccplot <- ggplot() + 
  geom_line(data=WQ, aes(x=Date, y=Secchi, color=StationCode, linetype=StationCode), size=1) +
  scale_color_viridis(discrete=TRUE)+
  theme_Publication() + #or whatever ggtheme you want
  labs(x = "Date", y = "Secchi Depth") +
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +# Changed date format 
  theme(axis.text.x = element_text(size = 8, angle =90))+ ##Changed dates to vertical
  theme(panel.grid.major = element_line(colour = "gray93",size=0.01), panel.grid.minor = element_blank())  #stylist choice, you can mess with this or not include it at all to stay with the R default
  #labs(colour = "Site") +
  #theme(plot.title = element_text(hjust = 0.5)) #not necessary

Seccplot
```
#pH
```{r}

##Remove outliers on 12-26&27/2018 PH super low, CDEC Data normal, must be probe on same YSI
WQpH <- filter(WQ, !pH<= 6.5)

pHplot <- ggplot() + 
  geom_line(data=WQpH, aes(x=Date, y=pH, color=StationCode, linetype=StationCode), size=1) +
  scale_color_viridis(discrete=TRUE)+
  theme_Publication() + #or whatever ggtheme you want
  labs(x = "Date", y = "pH") +
  scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y") +# Changed date format 
  theme(axis.text.x = element_text(size = 8, angle =90))+ ##Changed dates to vertical
  theme(panel.grid.major = element_line(colour = "gray93",size=0.01), panel.grid.minor = element_blank()) 
pHplot

ggplotly(pHplot)
```
#Turbitiy and Secchi #Already in WQ QAQC 

```{r}
##Combining Graphs using grid arrange function 

#install.packages("gridExtra")
library(gridExtra)
library(grid)
#g1<- as_grob(tempplot)

jpeg("WQall.jpeg",quality = 75,width = 700, height= 500)
grid.arrange(tempplot,DOplot,turbplot,pHplot,SpCndplot)
   dev.off()   

   WQAll<-  grid.arrange(tempplot,DOplot,turbplot,pHplot,SpCndplot, 
      ncol = 1, nrow = 5)
   
   tiff(filename = "PhytoChloroOutputFigs/WQAll.tiff", res = 500, width = 10, height = 12, family = "sans", units = "in", compression = "lzw")
grid.arrange(tempplot,DOplot,turbplot,pHplot,SpCndplot, 
      ncol = 1, nrow = 5)
dev.off()
# tiff(filename = "WQFigs/allWQ.tiff", res = 300, width = 7, height= 5, family = "sans", units = "in", compression = "lzw")
# (g1) 
# 
# dev.off()  ##I guess this doesnt work for gridarrange

?jpeg
   
   
  WQ2<- pivot_longer(WQpH, cols = c(5,8,9,10,11),values_to = "Value", names_to = "Parameter")
  
  WQ3<-ggplot(WQ2)+
    geom_line(aes(x=Date,y=Value, color=StationCode, linetype=StationCode), size = 1.2)+
    geom_point(aes(x = Date, y = Value, color = StationCode, shape = StationCode), size = 2.1) +
     scale_color_viridis(discrete=TRUE)+
     theme_Publication() + #or whatever ggtheme you want
     #labs(x = "Date", y = "") +
    facet_wrap(~Parameter, scales="free_y",nrow=5, strip.position = "left",labeller = as_labeller(c(DO = "DO \n(mg/L)", pH = "pH",SpCnd="SpCnd \n(mS/cm)", Turbidity="Turbidity \n(FNU)", WaterTemp="Water Temp \n(°C)")))+
    theme(strip.background = element_rect(fill="White", color = "White"),
          strip.placement = "outside", axis.title.y = element_blank(), legend.position = "top")+
    
      scale_x_date(date_breaks = "3 months", date_labels= "%b-%Y")+
    scale_linetype_manual(values = c("dotted", "solid", "longdash"))+
    theme(axis.text.x = element_text(size = 13, angle =90), axis.text.y = element_text(size = 13), strip.text = element_text(size = 13),legend.text = element_text(size = 13), legend.title = element_text(size = 13), axis.title.x = element_blank())

    WQ3
    
tiff(filename = "WY2017_WY2019/figures/fig_WQAll.tiff", res = 300, width = 10, height = 12, family = "sans", units = "in", compression = "lzw")
(WQ3)
dev.off()
```

