---
title: "Nutrients_Plot_Code_Report"
author: "Parisa Farman"
date: "1/26/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r set-options, echo=FALSE, cache=FALSE}

options(fig.width = 12)
rm(list=ls(all=TRUE))
```

## 1.Setup and Download libraries

```{r setup, results=FALSE, warning = FALSE, message = FALSE}

rm(list=ls(all=TRUE))

library(tidyverse)
library(grid)
library(zoo)
library(lubridate)
library(gridExtra)
library(knitr)
library(plotly)
library(rcompanion)
library(stats)
library(viridis)
library(ggthemes)
library(plyr)
library(magrittr)
library(readxl)
library(extrafont)
library(dplyr)
library(scales)
#install.packages("tiff")
library(tiff)

```

```{r}
theme_ltreport <- theme_bw() + 
  theme(axis.text = element_text(size = 14),
                        axis.title.x = element_blank(),
                        strip.text = element_text(size = 13),
                        axis.text.x = element_text(angle = 90),
                        legend.title = element_text(size = 11),
                        legend.text = element_text(size = 9.5),
        legend.position = "top",
        axis.title.y = element_text(size = 10,
                                    margin = margin(l=3)))
```

## 2.Load Data and Restructure Dataframe

```{r load, results = FALSE, warning = FALSE, message = FALSE}
#setup
#setwd("X:\\YB_Manuscripts, Reports, Newsletters (AEU)\\YoloBypass_AnnualReport_LowerTrophic\\Lower Trophic Report_2017-2019\\Nutrients\\Data")
#Nutrients_raw <- read_excel(path = "WQ_discrete_nutrients_RAW_2022_PF.xlsx")
root <- "WY2017_WY2019/nutrients/Data"
Nutrients_raw <- read_excel(here::here(root, "WQ_discrete_nutrients_RAW_2022_PF.xlsx"))

#checking data structure
str(Nutrients_raw) ##Note that Results are characters because of <R.L., will need to be as.numeric for plotting

#Using as.date  
Nutrients_raw$Date <- as.Date(Nutrients_raw$Date)
Nutrients_raw$Time <- as.character(Nutrients_raw$Time)
str(Nutrients_raw)

##Get rid of WY 2020 values 
Nutrients_raw <- filter(Nutrients_raw, Date < "2019-10-1")

# Restructuring data/adding new month, year, and datetime column

Nutrients_raw$Time <-  ymd_hms(Nutrients_raw$Time)

Nutrients_raw$Time2 <- strptime(Nutrients_raw$Time, format = "%Y-%m-%d %H:%M:%S") %>%
  strftime(Nutrients_raw$Time, format = "%H:%M:%S")

str(Nutrients_raw)#check

Nutrient_data <- Nutrients_raw %>% mutate(Datetime = paste(Date, Time2, sep = " "))
Nutrient_data$Year <- year(Nutrient_data$Date)
Nutrient_data$Month <- factor(month(Nutrient_data$Date))
mymonths <- c("Jan","Feb","Mar",
              "Apr","May","Jun",
              "Jul","Aug","Sep",
              "Oct", "Nov", "Dec")
#add abbreviated month name
Nutrient_data$MonthAbb <- mymonths[Nutrient_data$Month ]
#set order of months
Nutrient_data$MonthAbb <-ordered(Nutrient_data$MonthAbb,levels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))

#delete/filter out duplicates 
Nutrient_data_Normal <- Nutrient_data %>%
  filter(Purpose == "Normal Sample") %>%
  group_by(StationCode, Analyte, Datetime, Date, Time2, Month, MonthAbb, Year) %>%
  slice(1)
#Removing duplicates that aren't labeled 
Nutrient_data_Normal %>% group_by (StationCode, Datetime, Analyte) %>% filter(duplicated(Result))

#remove columns that are not needed
Data_filtered<- select(Nutrient_data_Normal, -c(Time,Units:Purpose))
Data_filtered <- filter(Data_filtered, Analyte %in% c("DisAmmonia", "DisNitrateNitrite","DisSilica","DOP"))
```

## 3. Check for outliers 
```{r}
Data_outlier <- Data_filtered %>% filter (StationCode=="STTD", Analyte=="DisNitrateNitrite", Result!="< R.L.") %>% mutate(Result=as.numeric(Result)) 
  
Analyte_Q1 = quantile(Data_outlier$Result, prob = 0.25) 
#0.065
Analyte_Q3 = quantile(Data_outlier$Result, prob = 0.75)
#0.238
Analyte_UL = Analyte_Q3 + 1.5 * (Analyte_Q3-Analyte_Q1)
#0.499 

Data_outlier_test <- Data_outlier %>% mutate(UL=Analyte_UL) %>% mutate(median=(median(Data_outlier$Result))) %>% mutate(MAD=(mad(Result))) %>% mutate(MODZ=(abs(0.6745*(Result-median)/MAD)))
#Greater than UL

Data_outlier_MAD = mad(Data_outlier_test$median) %>% mutate(MAD=abs(0.6745*((Result-median)/MAD)))


#remove outliers 

Data_filtered <- Data_filtered [-c(24,790,815),]

```

## 4. Set up plot 

```{r}
#make sign column 
Data_sign<- mutate(Data_filtered, Sign=ifelse(Result=="< R.L.", "<", "="))
Data_sign<- mutate(Data_sign, Result=ifelse(Result=="< R.L." & Analyte=="DisAmmonia" & Date>="2018-11-27", 0.05, ifelse(Result=="< R.L." & Analyte=="DisAmmonia" & Date<"2018-11-27", 0.01,ifelse(Result=="< R.L." & Analyte=="DisNitrateNitrite" & Date>="2018-11-27", 0.05, ifelse(Result=="< R.L." & Analyte=="DisNitrateNitrite" & Date<"2018-11-27", 0.01, ifelse(Result=="< R.L." & Analyte=="DOP" & Date>="2018-11-27", 0.05, ifelse(Result=="< R.L." & Analyte=="DOP" & Date<"2018-11-27", 0.01,ifelse(Result=="< R.L." & Analyte== "DisSilica", 0.1, Result))))))))

#changing to numeric values for result column 
Data_sign$Result <- as.numeric(as.character(Data_sign$Result))
str(Data_sign)

Data_sign$StationCode <- factor(Data_sign$StationCode, levels = c("LIS", "STTD", "SHR"))

##Creating segments for horz and vert portions of graph

seg_subset <- subset (Data_sign, Data_sign$Sign == '<')

df_seg_vert <- data.frame(x=seg_subset$Date, xend = seg_subset$Date,
                          y=0, yend=seg_subset$Result,
                          Analyte=seg_subset$Analyte, 
                          StationCode = seg_subset$StationCode, 
                          stringsAsFactors = FALSE)
df_seg_horz = data.frame(
  x = seg_subset$Date-3,
  xend = seg_subset$Date+3,
  y = seg_subset$Result,
  yend = seg_subset$Result,
  Analyte = seg_subset$Analyte,
  StationCode = seg_subset$StationCode,
  stringsAsFactors = FALSE
)
```


## 5. Analyte Plots

```{r plots}

DisAmmonia <- filter(Data_sign, Analyte=="DisAmmonia")
DisAmmonia_vert <- filter(df_seg_vert, Analyte=="DisAmmonia")
DisAmmonia_horz <- filter(df_seg_horz, Analyte=="DisAmmonia")
(pDisAmmonia <- ggplot() +
        geom_segment(data = DisAmmonia_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lty = 5) +
        geom_segment(data = DisAmmonia_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lineend = 'square') +
        geom_line(DisAmmonia, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 1.1) +
        geom_point(DisAmmonia, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 2) + 
    scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") + 
  labs(title = "A) Dissolved Ammonia", y="Dissolved Ammonia (mg/l as N)", size=12) + 
  scale_color_viridis(discrete=TRUE) +
    theme_ltreport)
 #   theme(axis.text.x=element_text(angle=90, size=12),axis.title.x=element_blank()) + 
  #theme(axis.text.y=element_text(size=12)))

DisNitrateNitrite <- filter(Data_sign, Analyte=="DisNitrateNitrite")
DisNitrateNitrite_vert <- filter(df_seg_vert, Analyte=="DisNitrateNitrite")
DisNitrateNitrite_horz <- filter(df_seg_horz, Analyte=="DisNitrateNitrite")
(pDisNitrateNitrite <- ggplot() +
        geom_segment(data = DisNitrateNitrite_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lty = 5) +
        geom_segment(data = DisNitrateNitrite_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lineend = 'square') +
        geom_line(DisNitrateNitrite, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 1.1) +
        geom_point(DisNitrateNitrite, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 2) +
   scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") + 
  labs(title = "B) Dissolved Nitrate-Nitrite", 
       y="Dissolved Nitrate-Nitrite (mg/L as N)", size=12) +
  theme_ltreport + scale_color_viridis(discrete=TRUE)) 
#  theme(axis.text.x=element_text(angle=90, size=12), axis.title.x=element_blank()) +
#    theme(axis.text.y=element_text(size=12)))


DisSilica <- filter(Data_sign, Analyte=="DisSilica")
DisSilica_vert <- filter(df_seg_vert, Analyte=="DisSilica")
DisSilica_horz <- filter(df_seg_horz, Analyte=="DisSilica")
(pDisSilica <- ggplot() +
        geom_segment(data = DisSilica_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lty = 5) +
        geom_segment(data = DisSilica_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lineend = 'square') +
        geom_line(DisSilica, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 1.1) +
        geom_point(DisSilica, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 2) +
   scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") + 
  labs(title = "D) Dissolved Silica", y="Dissolved Silica (mg/L)") + 
  theme_ltreport + scale_color_viridis(discrete=TRUE))
 # theme(axis.text.x=element_text(angle=90, size =12), axis.title.x=element_blank())+
  #  theme(axis.text.y=element_text(size=12)))

DOP <- filter(Data_sign, Analyte=="DOP")
DOP_vert <- filter(df_seg_vert, Analyte=="DOP")
DOP_horz <- filter(df_seg_horz, Analyte=="DOP")
(pDOP <- ggplot() +
        geom_segment(data = DOP_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lty = 5) +
        geom_segment(data = DOP_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .8, lineend = 'square') +
        geom_line(DOP, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 1.1) +
        geom_point(DOP, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 2) +
   scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") + 
  labs(title = "C) Dissolved Orthophosphate", y="Dissolved Orthophosphate (mg/L as P)") + 
  theme_ltreport + scale_color_viridis(discrete=TRUE)) 
  #theme(axis.text.x=element_text(angle=90,size =12), axis.title.x=element_blank())+
   #  theme(axis.text.y=element_text(size=12)))


```
#6. Inundation-Analyte Plots
```{r}

Inun_Data <- read_xlsx(here::here(root, "InundationWY2010toWY2019.xlsx"))

str(Data_sign_inun)
Inun_Data_Filtered <- filter(Inun_Data, Date >= "2016-10-01", Date <= "2019-09-30")

Inun_Data_Filtered$Date <- as.Date(Inun_Data_Filtered$Date)

Inun_Data_Filtered$color = ifelse(Inun_Data_Filtered$Inundation == TRUE, "Inundation", "No Inundation")

colors <- data.frame(Inun_Data_Filtered = c("Inundation", "No Inundation"), Color=c("light blue", "white"))

Inun_Data_Filtered$Inundation_n = ifelse(Inun_Data_Filtered$Inundation == "TRUE", 25, 0)
Inun_Data_Filtered$Inundation_amm = ifelse(Inun_Data_Filtered$Inundation == "TRUE",0.17, 0)
Inun_Data_Filtered$Inundation_nn = ifelse(Inun_Data_Filtered$Inundation == "TRUE",1.3, 0)
Inun_Data_Filtered$Inundation_dop = ifelse(Inun_Data_Filtered$Inundation == "TRUE",0.8, 0)

color = c("gray82", "white")

(pDisAmmonia_inun <- ggplot() +
    geom_col(data = Inun_Data_Filtered, aes(x=Date, y = Inundation_amm, fill = color, alpha = color)) +
    geom_segment(data = DisAmmonia_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lty = 5) +
    geom_segment(data = DisAmmonia_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lineend = 'square') +
    geom_line(DisAmmonia, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 0.9) +
    geom_point(DisAmmonia, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 1.5) +
    scale_alpha_manual(values = c(1,0), guide = "none") +  
    scale_fill_manual(values = color) +
   scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") + 
  labs(title = "A) Dissolved Ammonia", y="Dissolved Ammonia \n(mg/L as N)", fill = "Inundation") + 
  theme_ltreport + scale_color_viridis(discrete=TRUE, direction = -1) +
  theme(axis.text.x = element_blank(),
        legend.key=element_rect(colour="black")))



(pDisNitrateNitrite_inun <- ggplot() +
    geom_col(data = Inun_Data_Filtered, aes(x=Date, y = Inundation_nn, fill = color, alpha = color)) +
        geom_segment(data = DisNitrateNitrite_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lty = 5) +
        geom_segment(data = DisNitrateNitrite_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lineend = 'square') +
        geom_line(DisNitrateNitrite, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 0.9) +
        geom_point(DisNitrateNitrite, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 1.5) +
   scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") +
        scale_alpha_manual(values = c(1,0), guide = "none") + 
    scale_fill_manual(values = color) +
  labs(title = "B) Dissolved Nitrate-Nitrite", y="Dissolved Nitrate-Nitrite \n(mg/L as N)", fill = "Inundation")+ 
  theme_ltreport + scale_color_viridis(discrete=TRUE, direction = -1) +
  theme(axis.text.x = element_blank(),
        legend.key=element_rect(colour="black")))


(pDOP_inun <- ggplot() +
    geom_col(data = Inun_Data_Filtered, aes(x=Date, y = Inundation_dop, fill = color, alpha = color)) +
        geom_segment(data = DOP_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lty = 5) +
        geom_segment(data = DOP_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lineend = 'square') +
        geom_line(DOP, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 0.9) +
        geom_point(DOP, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 1.5) +
   scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") + 
        scale_alpha_manual(values = c(1,0), guide = "none") + 
    scale_fill_manual(values = color) +
  labs(title = "C) Dissolved Orthophosphate", y="Dissolved Orthophosphate \n(mg/L as P)", fill = "Inundation") + 
  theme_ltreport + scale_color_viridis(discrete=TRUE, direction = -1) +
  theme(axis.text.x = element_blank(),
        legend.key=element_rect(colour="black")))

(pDisSilica_inun <- ggplot() +  geom_col(data = Inun_Data_Filtered, aes(x=Date, y = Inundation_n, fill = color, alpha = color)) +
        geom_segment(data = DisSilica_vert, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lty = 5) +
        geom_segment(data = DisSilica_horz, mapping = aes(x = x, xend = xend, y = y, yend = yend, color = StationCode), size = .7, lineend = 'square') +
        geom_line(DisSilica, mapping = aes(Date, Result, group = StationCode, colour = StationCode), na.rm = TRUE,  size = 0.9) +
        geom_point(DisSilica, mapping = aes(Date, Result, group = StationCode, colour = StationCode, shape = StationCode), na.rm = TRUE, size = 1.5) +
   scale_x_date(date_breaks = "3 months", date_labels = "%b-%Y") + 
        scale_alpha_manual(values = c(1,0), guide = "none") +
    scale_fill_manual(values = color) +
  labs(title = "D) Dissolved Silica", y="Dissolved Silica (mg/L)", fill = "Inundation") + 
  theme_ltreport + scale_color_viridis(discrete=TRUE, direction = -1) +
  theme(legend.key=element_rect(colour="black")))

```


## 6. Print plots 
```{r}
tiff(filename = "4 analytes.tiff", res = 300, width = 12, height = 12, pointsize = 11, family = "sans", units = "in", compression = "lzw") 
(grid.arrange(pDisAmmonia, pDisNitrateNitrite, pDOP_inun, pDisSilica_inun, nrow=4)) 
dev.off() 

tiff(filename = "DisAmmonia.tiff", res = 300, width = 15, height = 5, pointsize = 11, family = "sans", units = "in", compression = "lzw") 
(pDisAmmonia) 
dev.off() 

tiff(filename = "DisNitrateNitrite.tiff", res = 300, width = 15, height = 5, pointsize = 11, family = "sans", units = "in", compression = "lzw") 
(pDisNitrateNitrite) 
dev.off() 

tiff(filename = "DisSilica.Inun.tiff", res = 300, width = 15, height = 5, pointsize = 11, family = "sans", units = "in", compression = "lzw") 
(pDisSilica_inun) 
dev.off() 

tiff(filename = "DOP.tiff", res = 300, width = 15, height = 5, pointsize = 11, family = "sans", units = "in", compression = "lzw") 
(pDOP) 
dev.off() 

tiff(filename = "DOP.Inun.tiff", res = 300, width = 15, height = 5, pointsize = 11, family = "sans", units = "in", compression = "lzw") 
(pDOP_inun) 
dev.off() 
```


## 7.Combined plots

```{r}
library(ggpubr)
(combinednuts <- ggarrange(pDisAmmonia_inun, pDisNitrateNitrite_inun,  pDOP_inun, pDisSilica_inun,nrow = 4, common.legend = TRUE, align = "v", heights = c(2,2,2,2.8)))
```

```{r}
tiff(filename = "WY2017_WY2019/figures/fig_inunnutrients.tiff", res = 300, width = 8, height = 9, pointsize = 11, family = "sans", units = "in", compression = "lzw")
combinednuts

dev.off()
```

